name: chalo_cart_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  web_socket_channel: ^3.0.2
  geolocator: ^13.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_secure_storage: ^9.0.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/assests/fonts/AlbertSans[wght].ttf
        - asset: assets/assests/fonts/AlbertSans-Italic[wght].ttf
          style: italic
