name: chalo_cart_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  geolocator: ^13.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/assests/images/
    - .env
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/assests/fonts/AlbertSans[wght].ttf
        - asset: assets/assests/fonts/AlbertSans-Italic[wght].ttf
          style: italic
