# ...existing code...
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # ...existing code...
    REQUIRED_FIELDS = ['email']  # Add other required fields if any
    # ...existing code...
